version: '3'
services:
  db:
    container_name: motoprostir_db
    image: postgres:10-alpine
    volumes:
    - data-postgres:/var/lib/postgresql/data
    ports:
    - 5431:5432
  api:
    container_name: motoprostir_api
#    command: bundle exec rackup config.ru -o 0.0.0.0 -p 3000
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/app:rw
    env_file:
    - .env
    ports:
    - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
    - db
    environment:
      DATABASE_URL: postgres://postgres@db
volumes:
  data-postgres:
    driver: local
